name: 功能请求
description: 为 OpenList Desktop 建议新功能
title: '[功能] '
labels: ['enhancement', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        感谢您建议新功能！请填写下面的表格，帮助我们理解您的请求。

  - type: textarea
    id: feature-description
    attributes:
      label: 功能描述
      description: 清楚简洁地描述您希望添加的功能。
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: 问题陈述
      description: 您的功能请求是否与某个问题相关？请描述此功能将解决什么问题。
      placeholder: 我总是因为...而感到困扰

  - type: textarea
    id: proposed-solution
    attributes:
      label: 建议的解决方案
      description: 描述您希望看到实现的解决方案。
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 考虑的替代方案
      description: 描述您考虑过的任何替代解决方案或功能。

  - type: dropdown
    id: feature-category
    attributes:
      label: 功能类别
      description: 此功能与应用程序的哪个领域相关？
      options:
        - 用户界面 / 用户体验
        - OpenList 服务管理
        - Rclone / 远程存储
        - 设置 / 配置
        - 日志 / 监控
        - 性能 / 优化
        - 安全 / 身份验证
        - 跨平台支持
        - 自动更新器
        - 其他
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 其他信息
      description: 在此处添加有关功能请求的任何其他信息、原型图或示例。

  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单
      description: 请确认以下内容
      options:
        - label: 我已搜索现有问题以确保此功能之前没有被请求过
          required: true
        - label: 此功能请求专门针对 OpenList Desktop（不是底层的 OpenList 或 Rclone 项目）
          required: true
